### ISSUE TITLE
Probleme in frame computing with Hidden Views in stack

### ISSUE THREAD

**Issue by vassily-fr** [barisatamer/StackViewSeparator#2]
If a view is hidden in the stack, then you should not compute its separator frame.
In "layoutSeparator"
to fix this use :
`let visibleItems = arrangedSubviews.filter({ $0.isHidden == false })`
`let previousSubView = visibleItems[index]`
`let currentSubivew = visibleItems[index + 1]`

instead of 
`let previousSubView = arrangedSubviews[index]`
 `let currentSubivew = arrangedSubviews[index + 1]`

**Comment by barisatamer** [comment]
Thank you @vassily-fr, fixed on version 0.1.3
